import numpy as np

from .activations import relu, softmax
from .batchnorm import apply_batchnorm


def linear_forward(A, W, b):
    """
    Implements the linear part of a layer's forward propagation.

    Parameters
    ----------
    A : ndarray
        The activations of the previous layer
    W : ndarray
        The weight matrix of the current layer (of shape [size of current layer, size of previous layer])
    b : ndarray
        The bias vector of the current layer (of shape [size of current layer, 1])

    Returns
    -------
    Z : ndarray
        The linear component of the activation function (i.e., the value before applying the non-linear function)
    cache : dict
        A dictionary containing A, W, b (stored for making the backpropagation easier to compute)
    """
    Z = np.dot(W, A) + b
    cache = {'A': A, 'W': W, 'b': b}
    return Z, cache


def linear_activation_forward(A_prev, W, b, activation, use_batchnorm=False):
    """
        Forward propagation for the LINEAR->ACTIVATION layer.

        Parameters
        ----------
        A_prev : ndarray
            Activations of the previous layer
        W : ndarray
            The weights matrix of the current layer
        b : ndarray
            The bias vector of the current layer
        activation : str
            The activation function to be used ("softmax" or "relu")
        use_batchnorm : bool, optional
            If True, applies batch normalization after activation (default is False)

        Returns
        -------
        A : ndarray
            The activations of the current layer
        cache : dict
            A joint dictionary containing both linear_cache and activation_cache
        """
    Z, linear_cache = linear_forward(A_prev, W, b)

    if activation == "relu":
        A, activation_cache = relu(Z)
    elif activation == "softmax":
        A, activation_cache = softmax(Z)
    else:
        raise ValueError(f"Unsupported activation function: '{activation}'. Expected 'relu' or 'softmax'.")

    if use_batchnorm:
        A = apply_batchnorm(A)

    cache = linear_cache | activation_cache
    return A, cache


def l_model_forward(X, parameters, use_batchnorm=False):
    """
        Implements forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SOFTMAX computation.

        Parameters
        ----------
        X : ndarray
            The input data of shape (input size, number of examples)
        parameters : dict
            The initialized W and b parameters of each layer
        use_batchnorm : bool, optional
            A flag to determine whether to apply batch normalization after the activation
            (set to False in Section 3 and True in Section 4)

        Returns
        -------
        AL : ndarray
            The last post-activation value
        caches : list of dict
            A list of all the cache objects generated by the linear_forward function
        """
    caches = []
    A = X
    L = len(parameters) // 2

    for l in range(1, L):
        A_prev = A
        A, cache = linear_activation_forward(A_prev, parameters[f"W{l}"], parameters[f"b{l}"], activation="relu",
                                             use_batchnorm=use_batchnorm)
        caches.append(cache)

    AL, cache = linear_activation_forward(
        A, parameters[f"W{L}"], parameters[f"b{L}"], activation="softmax"
    )
    caches.append(cache)

    return AL, caches
