def update_parameters(parameters, grads, learning_rate):
    """
    Updates parameters using gradient descent.

    Parameters
    ----------
    parameters : dict
        A dictionary containing the DNN architecture’s parameters
    grads : dict
        A dictionary containing the gradients (generated by l_model_backward)
    learning_rate : float
        The learning rate used to update the parameters (the “alpha”)

    Returns
    -------
    parameters : dict
        The updated values of the parameters object provided as input
    """
    L = len(parameters) // 2
    for l in range(1, L + 1):
        parameters[f"W{l}"] -= learning_rate * grads[f"dW{l}"]
        parameters[f"b{l}"] -= learning_rate * grads[f"db{l}"]
    return parameters
